// <auto-generated />
namespace UNSData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Org_houses1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Org_houses1));
        
        string IMigrationMetadata.Id
        {
            get { return "201907041637106_Org_houses1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
