// <auto-generated />
namespace UNS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _675 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_675));
        
        string IMigrationMetadata.Id
        {
            get { return "201910111523299_675"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
