// <auto-generated />
namespace UNS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _577 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_577));
        
        string IMigrationMetadata.Id
        {
            get { return "201908210838071_577"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
